[win] fallback to replace C++ keyword "inline" with C keyword "__inline" Otherwise depending on the VC-version, context, include-order it can cause:   error C2054: expected '(' to follow 'inline'