Fix [b7834045b9]: MS-VC 6 on core-8-6-branch: compile error C2520: conversion from unsigned __int64 to double not implemented, use signed __int64 No need to put it in change log, because regression was caused by [4128866276b86868]